/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FinalReservation } from './finalReservation';
import { PreReservation } from './preReservation';
import { Review } from './review';

export interface Activity { 
    id?: number;
    name?: string;
    description?: string;
    duration?: number;
    city?: string;
    adress?: string;
    zipCode?: string;
    price?: number;
    pictures?: Array<string>;
    maxParticipants?: number;
    category?: Activity.CategoryEnum;
    preReservations?: Array<PreReservation>;
    finalReservations?: Array<FinalReservation>;
    reviews?: Array<Review>;
}
export namespace Activity {
    export type CategoryEnum = 'SPORT' | 'EXTERIEUR' | 'DECOUVERTE';
    export const CategoryEnum = {
        SPORT: 'SPORT' as CategoryEnum,
        EXTERIEUR: 'EXTERIEUR' as CategoryEnum,
        DECOUVERTE: 'DECOUVERTE' as CategoryEnum
    };
}