/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FinalReservation } from './finalReservation';
import { PreReservation } from './preReservation';
import { Review } from './review';

export interface Activity { 
    id?: number;
    name?: string;
    description?: string;
    duration?: number;
    city?: string;
    adress?: string;
    zipCode?: string;
    price?: number;
    pictures?: Array<string>;
    maxParticipants?: number;
    category?: Activity.CategoryEnum;
    preReservations?: Array<PreReservation>;
    finalReservations?: Array<FinalReservation>;
    reviews?: Array<Review>;
}
export namespace Activity {
    export type CategoryEnum = 'AERIEN' | 'NEIGE' | 'AQUATIQUE' | 'NATURE' | 'PILOTAGE' | 'URBAIN';
    export const CategoryEnum = {
        AERIEN: 'AERIEN' as CategoryEnum,
        NEIGE: 'NEIGE' as CategoryEnum,
        AQUATIQUE: 'AQUATIQUE' as CategoryEnum,
        NATURE: 'NATURE' as CategoryEnum,
        PILOTAGE: 'PILOTAGE' as CategoryEnum,
        URBAIN: 'URBAIN' as CategoryEnum
    };
}