/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CurrentUserDTO { 
    id?: number;
    firstName?: string;
    lastName?: string;
    email?: string;
    role?: CurrentUserDTO.RoleEnum;
}
export namespace CurrentUserDTO {
    export type RoleEnum = 'PROFESIONAL' | 'PARTICULAR' | 'ADMIN';
    export const RoleEnum = {
        PROFESIONAL: 'PROFESIONAL' as RoleEnum,
        PARTICULAR: 'PARTICULAR' as RoleEnum,
        ADMIN: 'ADMIN' as RoleEnum
    };
}