/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Activity } from './activity';
import { User } from './user';

export interface FinalReservation { 
    id?: number;
    reservedAt?: Date;
    totalPrice?: number;
    payementDate?: Date;
    users?: Array<User>;
    activities?: Array<Activity>;
    status?: FinalReservation.StatusEnum;
}
export namespace FinalReservation {
    export type StatusEnum = 'PAID' | 'CANCELLED';
    export const StatusEnum = {
        PAID: 'PAID' as StatusEnum,
        CANCELLED: 'CANCELLED' as StatusEnum
    };
}